name: call_log_example
description: Demonstrates how to use the call_log plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  workmanager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  call_log:
    path: ../

flutter:
  uses-material-design: true